name: Publish Docker Images

on:
  push:
    branches:
      - 'main'
      - 'release'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: frontend
            context: ./worklenz-frontend
            file: ./worklenz-frontend/Dockerfile
            container_name: worklenz-frontend
          - name: backend
            context: ./worklenz-backend
            file: ./worklenz-backend/Dockerfile
            container_name: worklenz-backend
          - name: postgres
            context: .
            file: ./docker/postgres.Dockerfile
            container_name: worklenz-postgres
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.service.container_name }}
          tags: |
            type=raw,value=2.1.6-zh-TW.1
            type=ref,event=branch
          flavor: |
            latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
